### ISSUE TITLE
Device IDs

### ISSUE THREAD

**Issue by jsprada** [ricallinson/tpms#1]
Thank you for your work on this project!  I'm interesting in leveraging your efforts, but my application requires 5 sensors (4 tires in service, one full sized spare).

Do you know if each set of four have the same IDs as other sets of four, or do they have a larger pool of unique IDs?  Ideally, I can buy two sets in hopes to find 5 unique device IDs.   It would be a bummer to buy two sets, only to have two each of four different IDs.

**Comment by ricallinson** [comment]
Hey there, apologies for not seeing your message sooner. As far as I know the devices will/do have unique IDs. I've only bought one set the IDs appear to be randomly generated.

If your still looking into your project I can update the code to allow for a spare wheel. Let me know.
