### ISSUE TITLE
-duration command not recognized

### ISSUE THREAD

**Issue by devricardogalan** [ricallinson/tpms#2]
Hi ricallinson, first of all thanks for reading my question.

I'm not at all experimented on Go lang. So I tried your example and when get to the "go build" part, it says something about DefaultDevice. Exactly this.

**C:\Projects\Go\src\github.com\go-ble\ble\examples\lib\dev\dev.go:7:9: undefined:
 DefaultDevice**

Then when i try to run the command "**-duration 10s**"

**I get "-duration" is not recognized as an internal or external command, operable program or  batch file.**

So I wanted to know if there's a way to fix it or I'm missing something.

Thank you very much for your attention. 

Also I wanted to ask if this code  has a method to recognize specific sensors, by entering the number of the TPMS BLE Sensor or by scanning it.

**Comment by ricallinson** [comment]
Hey, thanks for the feedback. I'll update the README with detailed instructions. In the meantime try this and let me know if it works.

---

You must first install the `Go` environment for your operating system from [golang.org](https://golang.org/dl/). Once installed open your terminal program.

* MAC: Terminal. To open the terminal, `apple+space` and type `terminal`.
* Windows: Command Prompt. To open the command prompt, `windows+r` and type `cmd`.
* Linux: If you don't know you shouldn't be using Linux.

You should now see your command line interface. From here you will install the program and execute it. Enter the following at the command line;

	go get github.com/ricallinson/tpms
	go install github.com/ricallinson/tpms
	cd $GOPATH/src/github.com/ricallinson/tpms/examples/tpmssh
	go install
	tpmssh -duration 10s

The `tpmssh` should now run for ten seconds.

For subsequent uses you only need to start the program. No need to install it again.

	tpmssh -duration 10s

### Example Usage

The example can run indefinitely by excluding the `-duration` argument.

	tmpssh

Alternatively you can provide any number of seconds, minutes or hours for a monitoring duration.

	tmpssh -duration 30s
	tmpssh -duration 20m
	tmpssh -duration 24h

In all cases a log file will be written to `./log` containing the raw sensor data as a byte stream.

**Comment by ricallinson** [comment]
Forget the above post. I just tested the program on Windows and it doesn't compile. I'll look into the problem and see if I can fix it.

**Comment by devricardogalan** [comment]
> Forget the above post. I just tested the program on Windows and it doesn't compile. I'll look into the problem and see if I can fix it.

Thank you so much.
