### ISSUE TITLE
Trying Go for the first time :)

### ISSUE THREAD

**Issue by happyiphone** [ricallinson/tpms#3]
First of all thanks for sharing your time and effort on this!

Never used Go before but this seems to be a good excuse why to use it for the first time. I've got quite a few of this sensors and I want to read them programmatically. Seeing that you already went this route I would love to test what you have done already and try to follow lead. 

I installed go for Windows but as soon as I try to run the first command to get the repository cloned to my local machine I get this error message and I can't keep going:

```
c:\tpms>go get github.com/ricallinson/tpms
# github.com/go-ble/ble/examples/lib/dev
C:\Users\juand\go\src\github.com\go-ble\ble\examples\lib\dev\dev.go:9:9: undefined: DefaultDevice
```
Any help will be highly appreciated!

**Comment by happyiphone** [comment]
Not sure if it helps or not but this is the file causing the issue:

```
package dev

import (
	"github.com/go-ble/ble"
)

// NewDevice ...
func NewDevice(impl string, opts ...ble.Option) (d ble.Device, err error) {
	return DefaultDevice(opts...)
}
```

**Comment by ricallinson** [comment]
Hey there. You're correct with the problem import. Unfortunately the "go-ble" project doesn't support windows. I tried a few months ago to make it work but with no luck.

**Comment by happyiphone** [comment]
Perfect, thanks for getting back to me, I appreciate your effort shared on this project! I'll try to use the information here to see if I can read these sensors from a Win32 app. I'll use the tpms.go file, it seems that there is no CRC32 on the values reported by the sensors.
